### ISSUE TITLE
vest folder

### ISSUE THREAD

**Issue by rootsmusic** [christopherkenny/2020-census#1]
Christopher, I'm looking for an output file of step 4 in [your readme.md](https://github.com/christopherkenny/2020-census/blob/67df3c3bcb40785f0316b7ce2799f186ca57a7e4/vest2-vtd-2020/readme.md).  Are those in this repo's [vest folder](https://github.com/christopherkenny/2020-census/tree/main/vest)?  Thanks.

**Comment by christopherkenny** [comment]
The vest folder only contains the centroid matches.  The output of step 4 isn't retained due to the size of the upload that would be required. If you're interested in that output though, you can rerun the `vest2-vtd-2020/00_build.R` file, after removing the Step 5 section, which will avoid the re-aggregation.
